sudo: required
language: bash

# exclude tags.
branches:
  except:
    - /^\d+.\d+.\d+$/

services:
  - docker

env:
  global:
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER

before_install:
  - export CI_BUILD_NUMBER=$(if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then echo $CI_BUILD_NUMBER; else echo "${TRAVIS_BUILD_NUMBER}-SNAPSHOT"; fi)
  - echo "CI_BUILD_NUMBER=${CI_BUILD_NUMBER}"
  - if [ -n "$DOCKER_LOGIN" ]; then docker login --username $DOCKER_LOGIN --password $DOCKER_PASS; fi

script:
  - make $(if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then echo publish; else echo package; fi)

after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$(make version)
  - echo "GIT_TAG=$GIT_TAG"
  - >
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] &&
    git tag $GIT_TAG -f -a -m "Version $GIT_TAG built by Travis CI - https://travis-ci.org/$TRAVIS_REPO_SLUG/jobs/$TRAVIS_JOB_ID"
    || true
  - >
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] &&
    git push -q https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG --tags || true
